### ISSUE TITLE
Lumberjack loses connection after a few seconds

### ISSUE THREAD

**Issue by aggrofart** [peej/lumberjack-keyboard#10]
Hi, got another issue. When I plugged into my PC, VIA detects it for a few seconds but then stops detecting it. On Device Manager, the USB device was unknown and had a code 43 (Device descriptor request failed). I tried connecting it to another laptop and my friend's macbook but it could not be detected either. 
![mmc_fa4VNx6KDw](https://user-images.githubusercontent.com/114794250/205940246-7672ff86-914e-4f54-9670-b214dbcc7087.png)

You can check out a [short video that I recorded here for your reference](https://drive.google.com/file/d/1BxSn88kvvxoeLK0G6eAC08KTEaQVHmbv/view?usp=share_link). 
After leaving the board alone for >1 hour, I can connect it again and the issue repeats. 😅

Hope you can help with this! (:

**Comment by AldaCL** [comment]
If another computer didn't recognize the device it sounds like an ATMega issue or some charge remaining in the capacitors (which sounds very rare).

Did you already tried to reboot firmware/reload Bootloader?
Can you check if there is any short/bridge between adjacent pins?
Also you could check if there is some voltage drop on vcc/gnd, probably some of your components are generating some extra consume. 
Finally, when the device disconect, can you try to short the pins of the C3 capacitor, and check inmediatly if the device is recognized.

I had similar issue, but with intermittent connection/disconnects, the reason were some dust in the usb port

**Comment by aggrofart** [comment]
Thanks for the suggestions @AldaCL!

> _Did you already tried to reboot firmware/reload Bootloader?_
I tried pressing both reset and boot switches but the problem remains.

> _Can you check if there is any short/bridge between adjacent pins?_
None that I could see; attached some pics for reference.
![IMG_20221205_204535](https://user-images.githubusercontent.com/114794250/206485667-a776a3c3-7768-43ba-8414-844691bfaf2e.jpg)
![IMG_20221205_204824](https://user-images.githubusercontent.com/114794250/206485968-d8abb198-a349-472b-9fbc-4264d09391f7.jpg)

> _Also you could check if there is some voltage drop on vcc/gnd, probably some of your components are generating some extra consume._
How do I do this? I have a multimeter but am only used to checking for continuity. 😅

> _Finally, when the device disconect, can you try to short the pins of the C3 capacitor, and check inmediatly if the device is recognized._
Tried but still doesn't work. 😐

**Comment by aggrofart** [comment]
Hi, just to update that I desoldered the USB C connector (together with the R5, R6 resistors) and soldered on a mini USB connector instead to solve this issue. Closing this. Thanks for the help regardless! 😁
