### ISSUE TITLE
firmware error

### ISSUE THREAD

**Issue by Ventvo** [peej/lumberjack-keyboard#3]
PC does not recognize keyboard. Leds does not light up.
I flashed it with plaid firmware and it "worked" (LEDS lighted up and PC recognized it as keyboard. At keypress it was nonsence naturally, but i had some imput so its just matter of firmware).
Can you please provide firmware source code?

**Comment by peej** [comment]
The firmware source code is in the QMK repository: https://github.com/qmk/qmk_firmware/tree/master/keyboards/peej/lumberjack

**Comment by Ventvo** [comment]
Ok, I do understand it now.... I think.
I have the firmware compiled and can flash it trought Adrduino as ISP (verified).
But if i compile USBaspLoader, its about 2KB and EEPROM for bootloader is 1KB.
I dont know how can I make it fit.

**Comment by peej** [comment]
Are you talking about the firmware or the bootloader?

Once the chip is ISP flashed with the bootloader there should be no need to do this again, and the Lumberjack is compatible with the Plaid bootloader.

If you then want to rebuild the QMK firmware to change functionality, you can build and flash that as per the normal USB flashing procedure.

**Comment by Ventvo** [comment]
Thank you,
I just made it.
