### ISSUE TITLE
10k ohm resistor part number

### ISSUE THREAD

**Issue by rjorgenson-ns** [peej/lumberjack-keyboard#4]
Hi,

I am trying to build a lumberjack and going off the BOM the part number for the 10k ohm resistor of `CCF6010K0FKE36` appears to be a larger 8-10mm resistor that doesn't fit on the board design. Is there another part number for the smaller size resistor that will fit? This is the data sheet for the resistors I got from mouser based on the part number https://www.mouser.com/datasheet/2/427/VISH_S_A0001810520_1-2567648.pdf

**Comment by peej** [comment]
Oh good spot, sorry about that. You need the regular 6mm resistors, so something like `CMF5510K000BEBF` https://www.mouser.com/ProductDetail/?qs=Ymhh3MYumTmqMFwWXOXsVg%3D%3D (or https://www.aliexpress.com/item/32952657927.html if you want bulk from China).

I've updated the BOM on Octopart for all the resistors.

**Comment by rjorgenson-ns** [comment]
Awesome thanks, ordered some so I can get this build done =] can't wait!
