### ISSUE TITLE
LED 1/2 Purpose?

### ISSUE THREAD

**Issue by aggrofart** [peej/lumberjack-keyboard#9]
Hi! When I was testing the switch contacts, all work and light up LED 1 except for 3: MX6, 24 & 54. When I test the contacts for these 3, **LED 2** lights up instead and the corresponding keys do not register on my computer. 

Can I check what I did wrong? I checked the diodes and it appears to be soldered in the correct direction. 
![Troubleshoot Diodes MX6, 24, 54](https://user-images.githubusercontent.com/114794250/205494257-2c18ce90-b794-4a80-85d8-ca78b95c8833.jpg)

**Comment by peej** [comment]
In the default firmware in the QMK repo, LED1 is set to light up upon keypress, while LED2 on layer change, and keys 6, 24 and 54 are all bound in the default keymap to layer change, thus you see LED2 light up for these keys.

Layer changes also doesn't sent a OS recognisable keycode to your computer, so you won't see a keypress. If you are testing using VIA, you should enable matrix test mode to test all the keys.

**Comment by aggrofart** [comment]
Thanks, this really helped! I'll also use VIA to test the build out. 😁
